import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Owencodes | Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" type='image/png' href="/logo.png" />
      </Head>

      <main className={styles.main}>
        <h1 className="text-6xl font-bold">
          Owencodes
        </h1>
        <p className="text-4xl mt-10">Hi I'm Owen I am a Full Stack Developer!</p>
      </main>

      <footer className="">

      </footer>
    </div>
  )
}

export default Home
